// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwWo8km3aTE-FtGJry6F39n4F833TREE',
    appId: '1:79384365497:web:670b3109d205e57cfdce68',
    messagingSenderId: '79384365497',
    projectId: 'get-my-gps',
    authDomain: 'get-my-gps.firebaseapp.com',
    storageBucket: 'get-my-gps.appspot.com',
    measurementId: 'G-94SERG5Z7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8w4ova-WGTpnmjuA_8nHmzRahSU-d4B0',
    appId: '1:79384365497:android:eb13fa0dc74ab833fdce68',
    messagingSenderId: '79384365497',
    projectId: 'get-my-gps',
    storageBucket: 'get-my-gps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Asn9k6b-ZZymKdt3_9n3msxELKzs24E',
    appId: '1:79384365497:ios:b96d49b88ee11a1dfdce68',
    messagingSenderId: '79384365497',
    projectId: 'get-my-gps',
    storageBucket: 'get-my-gps.appspot.com',
    androidClientId: '79384365497-m1nkkqafntcq9pgssgl5t82j3crh2tj6.apps.googleusercontent.com',
    iosClientId: '79384365497-4mt0687gvn6h2j4dq1hjui852fa5relp.apps.googleusercontent.com',
    iosBundleId: 'com.example.getmygps',
  );
}
